name: RELEASE_APK_PUBLISH

on:
  workflow_dispatch:
  schedule:
    # Every nights at 4
    - cron: "0 4 * * *"

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx3072m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError" -Dkotlin.daemon.jvm.options="-Xmx2560m" -Dkotlin.incremental=false
  CI_GRADLE_ARG_PROPERTIES: --stacktrace -PpreDexEnable=false --max-workers 2 --no-daemon

jobs:
  nightly:
    name: RELEASE_APK_PUBLISH
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Install towncrier
        run: |
          python3 -m pip install towncrier
      - name: Prepare changelog file
        run: |
          yes n | towncrier build --version nightly
      - name: Build and upload Nightly APK
        run: |
          ./gradlew assembleNightly $CI_GRADLE_ARG_PROPERTIES
      - name: Upload release APKs
        uses: actions/upload-artifact@v3
        with:
          name: elementx-release
          path: |
            app/build/outputs/apk/release/*.apk
